### PR TITLE
add css properties to JSON output

### LINKED ISSUE #110: css properties missing from JSON output
It looks like the JSON output is missing the cssProp/cssProperty declarations from the jsdoc.

### PR DESCRIPTION
**Pull request by jrobinson01**
Add the css properties to the JSON output.
fixes #110

### CODE REVIEW

**Comment by web-padawan** [comment]
Thanks, and BTW this is something I also need in the `<api-viewer>` 👍

**Comment by web-padawan** [comment]
@runem would you have time to review this PR any time soon?

I was planning to implement CSS custom properties in the next `api-viewer` release.
This would be a really nice addition, and the proposed change seems good to me.

**Comment by runem** [comment]
Thanks for this PR @jrobinson01

I would really like to add "cssProperties" to the experimental custom-element.json format. Just to be clear: it might be removed if we land consensus on a custom-element.json format without "cssProperties" (this also applies to all other properties in the output) :-)

It might be relevant to start the discussion on adding "cssProperties" at https://github.com/webcomponents/custom-elements-json :+1:

I will merge this PR and also add support for https://github.com/runem/web-component-analyzer/issues/109 when I get home from work today :tada:

**Comment by web-padawan** [comment]
@runem could you release this change so we can use it?

**Comment by runem** [comment]
I have been more caught up in work than expected this week, sorry :-/ I just released 0.1.18 with css-properties for json-format :tada: and I will have some more time for web-component-analyzer this weekend :+1:

**Pull request merged**
