### PR TITLE
An aliased symbol can refer to multiple declarations.

### PR DESCRIPTION
**Pull request by rictic**
For example, a behavior is often declared as a type and a variable with the same name.

Fixes https://github.com/runem/web-component-analyzer/issues/63

### CODE REVIEW

**Comment by runem** [comment]
Thanks for the PR. It's great to see that snapshot tests for `@polymer/app-layout/app-drawer` now parse correctly! :tada:

**Comment by rictic** [comment]
Yeah! With this, all of google builds with no warnings! (after fixing a handful of legit warnings)

**Comment by web-padawan** [comment]
@rictic out of curiosity, are there any plans to incorporate this tool into Polymer project toolchain?

What's your developer experience with it, compared to `polymer-analyzer`?

Asking also because this sounds promising in terms of webcomponents.org reboot project.

**Comment by rictic** [comment]
My current thinking is that this family of tools is a solid replacement for both `polymer lint` and the Polymer IDE plugin for users of lit + TypeScript. That's definitely the direction that I'm pushing for our internal users to go.

The codebase has a lot of the good features of `polymer-analyzer`, it supports multiple different ways of writing elements, it builds up its own semantic, model. A lot of the changes are due to integrating tightly with TypeScript, which has a couple downsides (some parts of the lifecycle are synchronous that ideally would be async), and some big upsides (i.e. type checking templates!!!!!)

**Pull request merged**
